# Generated by Django 4.2 on 2023-05-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0001_initial'),
        ('user', '0002_collection_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='character_bookmarks',
            field=models.ManyToManyField(default=[], to='fanfic.character'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fandom_bookmarks',
            field=models.ManyToManyField(default=[], to='fanfic.fandom'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pairing_bookmarks',
            field=models.ManyToManyField(default=[], to='fanfic.pairing'),
        ),
    ]
