# Generated by Django 4.2.3 on 2023-07-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0002_alter_work_image'),
        ('user', '0004_alter_profile_lowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lowers',
            field=models.ManyToManyField(default=[], to='fanfic.work'),
        ),
    ]
