# Generated by Django 4.2 on 2023-05-28 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Fandom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(blank=True, choices=[('Books & Novels', 'Books & Novels'), ('Anime & Manga', 'Anime & Manga'), ('Real People', 'Real People'), ('Music & Musicals', 'Music & Musicals'), ('Video Games', 'Video Games'), ('Cartoons & Comics', 'Cartoons & Comics'), ('Movies', 'Movies'), ('TV Shows', 'TV Shows'), ('Other', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters', models.ManyToManyField(default=[], to='fanfic.character')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=300, unique=True)),
                ('image', models.ImageField(default='book.jpeg', upload_to='images/')),
                ('workType', models.CharField(choices=[('Work of my authorship', 'Work of my authorship'), ('Translation', 'Translation')], default='Work of my authorship', max_length=100)),
                ('fanfic_type', models.CharField(choices=[('Original', 'Original'), ('Fandom fan fiction', 'Fandom fan fiction')], default='Original', max_length=100)),
                ('raiting', models.CharField(choices=[('Whole audience', 'Whole audience'), ('Teenagers', 'Teenagers'), ('Mature', 'Mature'), ('Adults Only', 'Adults Only')], max_length=100)),
                ('orientation', models.CharField(choices=[('Gen', 'Gen'), ('Female/Male', 'Female/Male'), ('Male/Male', 'Male/Male'), ('Female/Female', 'Female/Female'), ('Multi', 'Multi'), ('Other', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('progressType', models.CharField(choices=[('In progress', 'In progress'), ('Finished', 'Finished'), ('Frozen', 'Frozen')], default='In progress', max_length=20)),
                ('public', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('characters', models.ManyToManyField(blank=True, to='fanfic.character')),
                ('fandoms', models.ManyToManyField(blank=True, to='fanfic.fandom')),
                ('pairings', models.ManyToManyField(blank=True, to='fanfic.pairing')),
                ('tags', models.ManyToManyField(default=[], to='fanfic.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fanfic.workcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanfic.work')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='fandom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanfic.fandom'),
        ),
        migrations.CreateModel(
            name='ChapterComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanfic.workcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('pre_text', models.TextField(max_length=1000)),
                ('text', models.TextField()),
                ('after_text', models.TextField(max_length=1000)),
                ('public', models.BooleanField(default=False)),
                ('place', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fanfic.work')),
            ],
        ),
    ]
