# Generated by Django 4.2 on 2023-05-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fandom',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
