# Generated by Django 4.2.3 on 2023-07-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, default='book.jpeg', upload_to='images/'),
        ),
    ]
