# Generated by Django 4.2 on 2023-05-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0002_alter_fandom_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='fandom',
            new_name='fandoms',
        ),
    ]
