# Generated by Django 4.2.1 on 2023-05-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0003_rename_fandom_work_fandoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
