# Generated by Django 4.2.1 on 2023-05-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0004_alter_work_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='work',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fanfic.work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(default='book.jpeg', upload_to='images/'),
        ),
    ]
