# Generated by Django 4.2.1 on 2023-05-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0005_chapter_work_alter_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='place',
            field=models.IntegerField(default=0),
        ),
    ]
