# Generated by Django 4.2 on 2023-05-27 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0006_chapter_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fanfic.workcomment'),
        ),
    ]
