# Generated by Django 4.2.1 on 2023-05-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='description',
            new_name='text',
        ),
    ]
