# Generated by Django 4.2.1 on 2023-05-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_description_about_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserConfirmation',
        ),
    ]
