# Generated by Django 4.2.1 on 2023-05-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_userconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanficrool',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='privatypolice',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
