# Generated by Django 4.2.1 on 2023-05-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_fanficrool_updated_privatypolice_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
