# Generated by Django 4.2 on 2023-05-19 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='https://images.pexels.com/photos/12442760/pexels-photo-12442760.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', upload_to='profile/')),
                ('backImage', models.ImageField(blank=True, upload_to='profile/background-image/')),
                ('about', models.TextField(blank=True)),
                ('coins', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('bookmarks', models.ManyToManyField(default=[], to='base.chapter')),
                ('lowers', models.ManyToManyField(default=[], to='base.work')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('works', models.ManyToManyField(default=[], to='base.work')),
            ],
        ),
    ]
